// [...table.children[1].children].map(x => [x.children[1]?.textContent, x.children[4]?.textContent]).filter(x => x[0] != null)

import { KanjiList } from "../types.ts";

export const kanjiN5: KanjiList = [
  ["日", "day, sun, Japan, counter for days"],
  ["一", "one"],
  ["国", "country"],
  ["人", "person"],
  ["年", "year, counter for years"],
  ["大", "large, big"],
  ["十", "ten, 10"],
  ["二", "two, 2"],
  ["本", "book, present, true, counter for long cylindrical things"],
  ["中", "in, inside, middle, mean, center"],
  ["長", "long, leader, superior, senior"],
  ["出", "exit, leave, go out"],
  ["三", "three, 3"],
  ["時", "time, hour"],
  ["行", "going, journey, carry out, line, row"],
  ["見", "see, hopes, chances, idea, opinion, look at, visible"],
  ["月", "month, moon"],
  ["分", "part, minute of time, understand"],
  ["後", "behind, back, later"],
  ["前", "in front, before"],
  ["生", "life, genuine, birth"],
  ["五", "five, 5"],
  ["間", "interval, space"],
  ["上", "above, up"],
  ["東", "east"],
  ["四", "four, 4"],
  ["今", "now; the present"],
  ["金", "gold"],
  ["九", "nine, 9"],
  ["入", "enter, insert"],
  ["学", "study, learning, science"],
  ["高", "tall, high, expensive"],
  ["円", "circle, yen, round"],
  ["子", "child"],
  ["外", "outside"],
  ["八", "eight, 8"],
  ["六", "six, 6"],
  ["下", "below, down, descend, give, low, inferior"],
  ["来", "come, due, next, cause, become"],
  ["気", "spirit, mind, air, atmosphere, mood"],
  ["小", "little, small"],
  ["七", "seven, 7"],
  ["山", "mountain"],
  ["話", "tale, talk"],
  ["女", "woman, female"],
  ["北", "north"],
  ["午", "noon, sign of the horse"],
  ["百", "hundred"],
  ["書", "write"],
  ["先", "before, ahead, previous, future, precedence"],
  ["名", "name, noted, distinguished, reputation"],
  ["川", "river, stream"],
  ["千", "thousand"],
  ["水", "water"],
  ["半", "half, middle, odd number, semi-"],
  ["男", "male; man"],
  ["西", "west"],
  ["電", "electricity; electric powered"],
  ["校", "school, exam"],
  ["語", "word, speech, language"],
  ["土", "soil, earth, ground"],
  ["木", "tree, wood"],
  ["聞", "to hear; to listen; to ask"],
  ["食", "eat, food"],
  ["車", "car, wheel"],
  ["何", "what"],
  ["南", "south"],
  ["万", "ten thousand, 10,000"],
  ["毎", "every"],
  ["白", "white"],
  ["天", "heavens, sky, imperial"],
  ["母", "mother"],
  ["火", "fire"],
  ["右", "right (direction)"],
  ["読", "to read"],
  ["友", "friend"],
  ["左", "left"],
  ["休", "rest, day off, retire, sleep"],
  ["父", "father"],
  ["雨", "rain"],
];

export const kanjiN4: KanjiList = [
  ["会", "meeting; meet"],
  ["同", "same, agree, equal"],
  ["事", "matter, thing, fact, business, reason, possibly"],
  ["自", "oneself"],
  ["社", "company, firm, office, association, shrine"],
  ["発", "departure, discharge, emit, start from"],
  ["者", "someone, person"],
  ["地", "ground, earth"],
  ["業", "business, vocation, arts, performance"],
  ["方", "direction, person, alternative"],
  ["新", "new"],
  ["場", "location, place"],
  ["員", "employee, member, number, the one in charge"],
  ["立", "stand up, rise"],
  ["開", "open, unfold, unseal"],
  ["手", "hand"],
  ["力", "power, strength, strong, strain, bear up, exert"],
  ["問", "question, ask, problem"],
  ["代", "substitute, change, convert, replace, period"],
  ["明", "bright, light"],
  ["動", "move, motion, change"],
  ["京", "capital"],
  ["目", "eye, class, look, insight, experience"],
  ["通", "traffic, pass through, avenue, commute"],
  ["言", "say, word"],
  ["理", "logic, arrangement, reason, justice, truth"],
  ["体", "body, substance, object, reality"],
  ["田", "rice field, rice paddy"],
  ["主", "lord, chief, master, main thing, principal"],
  ["題", "topic, subject"],
  ["意", "idea, mind, heart, taste, thought"],
  ["不", "negative, non-, bad"],
  ["作", "make, production, prepare, build"],
  ["用", "utilize, business, service, use, employ"],
  ["度", "degrees, occurrence, time, counter for occurrences"],
  ["強", "strong"],
  ["公", "public, prince, official, governmental"],
  ["持", "hold, have"],
  ["野", "plains, field, rustic, civilian life"],
  ["以", "by means of, because, in view of, compared with"],
  ["思", "think"],
  ["家", "house, home, family, professional, expert"],
  ["世", "generation, world, society, public"],
  ["多", "many, frequent, much"],
  ["正", "correct, justice, righteous"],
  ["安", "safe, peaceful, cheap"],
  ["院", "institution, temple, mansion, school"],
  ["心", "heart, mind, spirit"],
  ["界", "world, boundary"],
  ["教", "teach, faith, doctrine"],
  ["文", "sentence, literature, style, art"],
  ["元", "beginning, former time, origin"],
  ["重", "heavy, important, esteem, respect"],
  ["近", "near, early, akin, tantamount"],
  ["考", "consider, think over"],
  ["画", "brush-stroke, picture"],
  ["海", "sea, ocean"],
  ["売", "sell"],
  ["知", "know, wisdom"],
  ["道", "road-way, street, district, journey, course"],
  ["集", "gather, meet"],
  ["別", "separate, branch off, diverge"],
  ["物", "thing, object, matter"],
  ["使", "use, order, messenger, ambassador"],
  ["品", "goods, refinement, dignity, article"],
  ["計", "plot, plan, scheme, measure"],
  ["死", "death, die"],
  ["特", "special"],
  ["私", "private, I, me"],
  ["始", "commence, begin"],
  ["朝", "morning"],
  ["運", "carry, luck, destiny, fate, transport"],
  ["終", "end, finish"],
  ["台", "pedestal, a stand, counter for machines and vehicles"],
  ["広", "wide, broad, spacious"],
  ["住", "dwell, reside, live, inhabit"],
  ["無", "nothingness, none, ain't, nothing, nil, not"],
  ["真", "true, reality, Buddhist sect"],
  ["有", "possess, have, exist, happen"],
  ["口", "mouth"],
  ["少", "few, little"],
  ["町", "town, village, block, street"],
  ["料", "fee, materials"],
  ["工", "craft, construction"],
  ["建", "build"],
  ["空", "empty, sky, void, vacant, vacuum"],
  ["急", "hurry, emergency, sudden, steep"],
  ["止", "stop, halt"],
  ["送", "escort, send"],
  ["切", "cut, cutoff, be sharp"],
  ["転", "revolve, turn around, change"],
  ["研", "polish, study of, sharpen"],
  ["足", "leg, foot, be sufficient"],
  ["究", "research, study"],
  ["楽", "music, comfort, ease"],
  ["起", "wake up, get up; rouse"],
  ["着", "arrive, wear, counter for suits of clothing"],
  ["店", "store, shop"],
  ["病", "ill, sick"],
  ["質", "substance, quality, matter, temperament"],
  // page 2
  ["待", "wait, depend on"],
  ["試", "test, try, attempt, experiment"],
  ["族", "tribe, family"],
  ["銀", "silver"],
  ["早", "early, fast"],
  ["映", "reflect, reflection, projection"],
  ["親", "parent, intimacy, relative, familiarity"],
  ["験", "verification, effect, testing"],
  ["英", "England, English, hero, outstanding"],
  ["医", "doctor, medicine"],
  ["仕", "attend, doing, official, serve"],
  ["去", "gone, past, quit, leave, elapse, eliminate"],
  ["味", "flavor, taste"],
  ["写", "copy, be photographed, describe"],
  ["字", "character, letter, word"],
  ["答", "solution, answer"],
  ["夜", "night, evening"],
  ["音", "sound, noise"],
  ["注", "pour, irrigate, shed (tears), flow into, concentrate on"],
  ["帰", "homecoming, arrive at, lead to, result in"],
  ["古", "old"],
  ["歌", "song, sing"],
  ["買", "buy"],
  ["悪", "bad, evil, wrong"],
  ["図", "map, drawing, plan, extraordinary"],
  ["週", "week"],
  ["室", "room, apartment, chamber, greenhouse, cellar"],
  ["歩", "walk, counter for steps"],
  ["風", "wind, air, style, manner"],
  ["紙", "paper"],
  ["黒", "black"],
  ["花", "flower"],
  ["春", "spring"],
  ["赤", "red"],
  ["青", "blue"],
  ["館", "building, mansion, large building, palace"],
  ["屋", "roof, house, shop, dealer, seller"],
  ["色", "color"],
  ["走", "run"],
  ["秋", "autumn, fall"],
  ["夏", "summer"],
  ["習", "learn"],
  ["駅", "station"],
  ["洋", "ocean, sea, foreign, Western style"],
  ["旅", "trip, travel"],
  ["服", "clothing, admit, obey"],
  ["夕", "evening"],
  ["借", "borrow, rent"],
  ["曜", "weekday"],
  ["飲", "drink"],
  ["肉", "meat"],
  ["貸", "lend"],
  ["堂", "public chamber, hall"],
  ["鳥", "bird, chicken"],
  ["飯", "meal, rice"],
  ["勉", "exertion, endeavor, effort"],
  ["冬", "winter"],
  ["昼", "daytime, noon"],
  ["茶", "tea"],
  ["弟", "younger brother"],
  ["牛", "cow"],
  ["魚", "fish"],
  ["兄", "elder brother"],
  ["犬", "dog"],
  ["妹", "younger sister"],
  ["姉", "elder sister"],
  ["漢", "China"],
];
